server:
  port: 9096

spring:
  application:
    name: flight-route-service
  banner:
    location: banners/banner.txt

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: 123456
    username: multiservice
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: flight_route
        hbm2ddl:
          create_namespaces: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect